//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int Id { get; set; }
        public int FoodId { get; set; }
        public decimal Amount_g { get; set; }
        public int TimeOfMealId { get; set; }
        public int UserId { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual TimeOfMeal TimeOfMeal { get; set; }
        public virtual User User { get; set; }
    }
}
