//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Diary = new HashSet<Diary>();
            this.Allergy = new HashSet<Allergy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Energy_kJ { get; set; }
        public int Energy_kcal { get; set; }
        public int Protein_g { get; set; }
        public int Fat_g { get; set; }
        public int Carbohydrate_g { get; set; }
        public int Sodium_mg { get; set; }
        public int Potassium_mg { get; set; }
        public int Calcium_mg { get; set; }
        public int Magnesium_mg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diary> Diary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allergy> Allergy { get; set; }
    }
}
